#!/usr/bin/env python3
"""Generate an ARMCC-safe UTF-8 byte-array header for Chinese UI strings."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


NAME_PATTERN = re.compile(r"^[A-Z][A-Z0-9_]*$")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    values = json.loads(args.source.read_text(encoding="utf-8"))
    if not isinstance(values, dict):
        raise ValueError("UI string source must be a JSON object")

    lines = [
        "#ifndef _GREENMIND_UI_STRINGS_ZH_H",
        "#define _GREENMIND_UI_STRINGS_ZH_H",
        "",
        '#include "system.h"',
        "",
        "/* Generated by tools/fonts/generate_ui_strings.py. */",
    ]
    for name, text in values.items():
        if not isinstance(name, str) or not NAME_PATTERN.fullmatch(name):
            raise ValueError(f"invalid UI string name: {name!r}")
        if not isinstance(text, str) or not text:
            raise ValueError(f"invalid UI string value for {name}")
        payload = text.encode("utf-8") + b"\0"
        byte_text = ",".join(f"0x{value:02X}" for value in payload)
        lines.append(f"static const u8 GM_ZH_{name}[]={{" + byte_text + "};")

    lines.extend(["", "#endif", ""])
    output = "\n".join(lines)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="ascii")
    print(f"generated {args.output}: strings={len(values)} bytes={len(output)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
