#ifndef _TOUCH_SERVICE_H
#define _TOUCH_SERVICE_H

#include "app_state.h"

typedef enum
{
	APP_TOUCH_EVENT_NONE=0,
	APP_TOUCH_EVENT_HOME,
	APP_TOUCH_EVENT_DETAIL,
	APP_TOUCH_EVENT_AI_PAGE,
	APP_TOUCH_EVENT_SYSTEM,
	APP_TOUCH_EVENT_AI_REQUEST,
	APP_TOUCH_EVENT_NETWORK_RETRY,
	APP_TOUCH_EVENT_CALIBRATE,
	APP_TOUCH_EVENT_PLANT_LIBRARY,
	APP_TOUCH_EVENT_PLANT_ITEM_0,
	APP_TOUCH_EVENT_PLANT_ITEM_1,
	APP_TOUCH_EVENT_PLANT_ITEM_2,
	APP_TOUCH_EVENT_PLANT_ITEM_3,
	APP_TOUCH_EVENT_PLANT_ITEM_4,
	APP_TOUCH_EVENT_PLANT_ITEM_5,
	APP_TOUCH_EVENT_PLANT_BACK,
	APP_TOUCH_EVENT_PLANT_REFRESH,
	APP_TOUCH_EVENT_PLANT_USE
} AppTouchEvent;

void TouchService_Init(void);
AppTouchEvent TouchService_Task(AppPage page);
void TouchService_Adjust(void);

#endif
